### PR TITLE
Dino's places to eat in Detroit

### PR DESCRIPTION
**Pull request by azzurri2015**
@pboche what's your feedback on places to eat?

### CODE REVIEW

**Comment by pboche** [comment]
:hankey:

**Comment by pboche** [comment]
Where can I find Kale?

**Comment by azzurri2015** [comment]
There are some organic, urban farmers popping up in the neighborhoods which should have kale.  Don't forget to carry.

**Comment by barnieri** [comment]
Kale-fornia!

**Comment by pboche** [comment]
:+1:

**Pull request merged**
